project:
  type: website

website:
  title: "Welcome to Erik Lorimor's Data Science Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ejlorimor
format:
  html:
    theme: slate
    css: styles.css

editor: visual

