project:
  type: website

website:
  title: "Erik Lorimor"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - blog.qmd
      - text: "Resume"
        file: Resume_ErikLorimor.pdf
      - icon: github
        href: https://github.com/ejlorimor
format:
  html:
    theme: slate
    css: styles.css

editor: visual

